export const HOME_GET_BANNER_LIST = 'HOME_GET_BANNER_LIST' //获取banner
export const HOME_GET_NOWPLAYING_LIST = 'HOME_GET_NOWPLAYING_LIST' //获取首页热映电影
export const HOME_GET_COMINGSOON_LIST = 'HOME_GET_COMINGSOON_LIST' //获取首页即将上映电影